GLOBAL_X = 80
GLOBAL_Y = GLOBAL_X
TILE_SIZE = 10

TIME_RANGE = 180
HUMANS = int(GLOBAL_X * GLOBAL_X * .9)
HUMAN_MOVEMENT = int(HUMANS * .2)


# Cure
CHANCE_CURE = .2
TIME_UNTIL_CURED = int(TIME_RANGE * .1)

# Death
CHANCE_DEATH = .03
TIME_UNTIL_DEATH = int(TIME_RANGE * .033)
